---
label: Site Config
hide_body: false
fields:
- name: pathPrefix
  label: Pathprefix
  type: text
  hidden: false
  default: ''
- name: title
  label: Title
  type: text
  hidden: false
  default: ''
- name: description
  label: Description
  type: textarea
  hidden: false
  default: ''
- name: footer
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: true
    schema:
      format: html
  label: Footer
  description: Content to display in site footer
